---
language: generic

services:
  - docker

before_install:
- docker pull testthedocs/ttd-linkcheck
- docker pull testthedocs/ttd-remark
- docker pull testthedocs/vale-demo

stages:
  - linkcheck

jobs:
  include:
    - stage: linkcheck
      script: docker run -v `pwd`/docs:/srv/test testthedocs/ttd-linkcheck docs

      #script: docker run --rm -i -v `pwd`:/lint/input:ro testthedocs/ttd-remark docs
      #script: docker run -it -v `pwd`/docs:/srv/tests testthedocs/vale-demo

#script:
#- docker run -v `pwd`/docs:/srv/test testthedocs/ttd-linkcheck docs
#- docker run --rm -i -v `pwd`/docs:/lint/input:ro testthedocs/ttd-remark .
#- docker run --rm -i -v `pwd`:/lint/input:ro testthedocs/ttd-remark docs
#- docker run -it -v `pwd`/docs:/srv/tests testthedocs/ttd-vale
#- docker run -it -v `pwd`/docs:/srv/tests testthedocs/vale-demo
