---
language: generic
dist: xenial

services:
  - docker

stages:
  - test
  - building

jobs:
  include:
    - stage: test
      script:
      - docker run -v `pwd`/docs:/srv/test testthedocs/ttd-linkcheck docs
      - docker run --rm -i -v `pwd`:/lint/input:ro testthedocs/ttd-remark docs
      - docker run -it -v `pwd`/docs:/srv/tests testthedocs/vale-demo
    - stage: build and deploy
      script:
      - docker run -it --rm -v `pwd`:/docs testthedocs/ttd-mkdocs:latest build
      - .ci/deploy.sh



