site_name: CI Demo
site_description: 'Write Drunk - Test Automated'
site_author: 'TestTheDocs'
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'white'
    accent: 'light blue'
    #  feature:
    #tabs: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository
repo_name: svx/demo
repo_url: https://github.com/svx/demo
edit_uri: ""

# Copyright
copyright: 'Copyleft &copy; 2019 - svx & TestTheDocs'

# Page tree
nav:
  - Home: index.md
  - Docs as Code: docs-as-code.md
