---
version: 2

jobs:
  "linkcheck":
    docker:
      - image: testthedocs/ttd-linkcheck
    steps:
      - checkout
      - run:
          command: |
            su-exec ttd /usr/local/bin/linkcheck -c '200,301,302' -t 5 docs

  "markdown":
    docker:
      - image: zemanlx/remark-lint
    steps:
      - checkout
      - run:
          docker run --rm -i -v $PWD/docs:/lint/input:ro zemanlx/remark-lint .

workflows:
  version: 2
  btd:
    jobs:
      - "linkcheck"
      - "markdown"
