---
version: 2

jobs:
  "linkcheck":
    docker:
        - image: testthedocs/cci-linkcheck:0.0.2
    steps:
      - checkout
      - run:
          command: |
            su-exec ttd /usr/local/bin/linkcheck -c '200,301,302' -t 5 docs

  "vale":
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          command: |
            go get github.com/ValeLint/vale
            vale docs/*.md

workflows:
  version: 2
  btd:
    jobs:
      - "linkcheck"
      - "vale"
