---
version: 2

jobs:
  "linkcheck":
    docker:
      - image: testthedocs/ttd-linkcheck
    steps:
      - checkout
      - run:
          command: |
            su-exec ttd /usr/local/bin/linkcheck -c '200,301,302' -t 5 docs

  "vale":
    docker:
      - image: testthedocs/ttd-vale
    steps:
      - checkout
      - run:
          command: |
            su-exec ttd vale --config='/srv' docs

workflows:
  version: 2
  btd:
    jobs:
      - "linkcheck"
      - "vale"
